resources:
- name: Millenium
  type: time
  source:
    interval: 1m
- name: source-code
  type: git
  source:
    uri: https://github.com/sthaniraj/myapp.git
    branch: master
jobs:
- name: hello-world
  plan:
  - get: Millenium
    trigger: true
  - get: source-code
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
